### PR TITLE
added flutter_web_frame. Showcasing

### PR DESCRIPTION
**Pull request by Jesse-Lucas1996**
image

Wow it's beautiful

### CODE REVIEW

**Comment by Jesse-Lucas1996** [comment]
@hungps Wow flutter_web_frame works really well and pretty easy?
What do you think?

**Comment by hungps** [comment]
@Jesse-Lucas1996 
Could you try to wrap the whole `MaterialApp` inside `lib/app.dart` with `FlutterWebFrame`?
Like this:

```
class PokedexApp  extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
     return FlutterWebFrame(
       maximumSize: Size.fromWidth(1200),
       enabled: !Platform.isAndroid && !Platform.isIOS,
       builder: (_) => MaterialApp(
         ....
       ),
     );
  }
}
```

**Comment by Jesse-Lucas1996** [comment]
@hungps Done!! It looks beautiful now

**Comment by hungps** [comment]
@Jesse-Lucas1996 Looking good! Please push your newest code and I will merge them into `master`.

**Comment by Jesse-Lucas1996** [comment]
Where else did you want me to add it? @hungps

**Comment by hungps** [comment]
@Jesse-Lucas1996 
Changing the background color based on the current theme is also great. Please change the `FlutterWebFrame` properties to these:

```
maximumSize: Size.fromWidth(400),
enabled: !Platform.isAndroid && !Platform.isIOS,
backgroundColor: isDark ? Colors.black12 : Colors.grey[200],
```

**Comment by Jesse-Lucas1996** [comment]
@hungps Done :) I changed from 400 to 600 for from Width, imo it looks better but if you prefer 400 we can go with it :) you're the bossman

**Comment by hungps** [comment]
@Jesse-Lucas1996 `Platform.isAndroid` and `Platform.isIOS` seems to not working on the web. Please change `enabled` to `kIsWeb || !Platform.isAndroid && !Platform.isIOS`

**Comment by Jesse-Lucas1996** [comment]
Have added @hungps

**Comment by Jesse-Lucas1996** [comment]
@hungps just give me a ping if you want anything else done!

**Pull request merged**
