### PR TITLE
Dark and Light theme switching done

### PR DESCRIPTION
**Pull request by jinosh05**
This commit contains all the screens with theme switching.

Need to be improved and will be updated soon

### CODE REVIEW

**Comment by hugovidafe** [comment]
I'm trying to check and test this PR.
But for some reason, I cannot build an apk.
image


Is there any method to change the buildToolsVersion to an upper version? I tried this way, but no result D:
image

**Comment by jinosh05** [comment]
Hello there,
Try upgrading the flutter SDK to latest version. Shall I send the release
apk if you need?

Thank you

**Comment by hungps** [comment]
Hi @jinosh05, I've tried running this code with the newest version of Flutter and it works great!
However, there are some things I'd like you to do before merging to make it even better:
- Update the Flutter version in the `.fvm/fvm_config.json` to `3.0.3`
- Bring the Dark/Light toggle button down a little bit to avoid the safe area.
- The background of the Pokemon News should be lighter compared to the header
- The All Gen and the Search modal is still in white
- The Heart icon on the Pokedex screen's header should be white

**Comment by jinosh05** [comment]
All changes are updated and tested now, check it out and merge it

**Comment by hungps** [comment]
@jinosh05 This two modals are still in white, could you please update it?

**Comment by jinosh05** [comment]
Applied changes to those cards

**Comment by hungps** [comment]
@jinosh05 Thank you!

**Pull request merged**
