### PR TITLE
[Urgent] Update the Pokemon source url

### PR DESCRIPTION
**Pull request by Hugovidafe**
Actually, nothing is showing
image

### CODE REVIEW

**Comment by hungps** [comment]
Hi @Hugovidafe, this bug has been fixed in #52, I cannot reproduce the problem in the latest code.
Could you please update the code in your local machine to the latest `master` and see if it is working or not? Thank you!

**Comment by Hugovidafe** [comment]
I just download https://codemagic.io/app/5d3727997dee22001bb7681c/build/61f974c029657a000ba19d82 from the last commit on master... Check the url on the files changed section.

**Comment by hungps** [comment]
@Hugovidafe Oh, the current url is working fine. But I spotted that the line `<uses-permission android:name="android.permission.INTERNET"/>` is gone in `android/src/main/AndroidManifest.xml` since I did the #53 one, that's the reason why it cannot fetch the data on the release build but still working in debug mode. Thank you so much for raising the problem, I haven't noticed that since then!

Because you've already opened this PR, could you please add the missing line to it? Thank you!

**Comment by Hugovidafe** [comment]
Ready! 🤗

**Comment by hungps** [comment]
Thank you!

**Comment by Hugovidafe** [comment]
No problem!

**Comment by Hugovidafe** [comment]
The first time I saw this warning when I tried to install this app after downloading it from CodeMagic

**Comment by hungps** [comment]
@Hugovidafe It's because the app is currently signed using the debug keystore only for demo purposes. Don't worry about it!

**Pull request merged**
